default:
  stackName: ram-demo-test-cf-3
  bucket: ram-demo-test
  capabilities:
    - CAPABILITY_NAMED_IAM

  vpc:
    id: vpc-dfe524ba
    subnet: subnet-7945cb75

  rds:
    type: db.t2.small
    username: ram
    password: '{{DB_PASSWORD}}'
    dbName: ram
    engine: postgres
    version: '9.6.8'
    storage: 20

  # instances created by this config are configured to work with ECS service
  ecs:
    publicIp: true # whether the ec2 instance have public IP addresses
    availabilityZone: us-east-1f # IMPORTANT: subnet and availability zone must be in the same zone
    amiid: ami-aff65ad2 # which ec2 AMI to use for the ec2 instances
    keyPairName: ruralroads # the ssh key to use for login into instance
    ec2:
      api:
        instanceType: t2.medium # size of the ec2 instance
        volumeSize: 30
      frontend:
        instanceType: t2.micro
        volumeSize: 8

  taskDefinitions:
    ramApi:
      count: 1
      volume:
        name: pos
        path: /var/lib/postgresql/data # this is the path on the source machine
      containers:
        ram-api:
          image: wbtransport/ram-backend:latest-dev
          #cpu: 10 # this is an optional key
          memory: 2000 # defaults to 256mb
          ports:
            - host: 80
              container: 4000 
              protocol: tcp
          commands:
            - node
            - index.js
          includeRds: true # set to true if RDS is used. DB_URI will be set automatically
          envs:
            INSTANCE_ID: ram-aws-test
            DS_ENV: staging
            CLUSTER: '!Ref ECSCluster'
            VT_TASK_DEF: '!Ref ramVectorTilesTaskDefinition'
            ANL_TASK_DEF: '!Ref ramAnalysisTaskDefinition'
            RAH_GH_REPO: 'WorldBank-Transport/rah'
            RAH_GH_TOKEN: '{{RAH_GH_TOKEN}}'
            RAH_GH_PATH: 'app/assets/content/projects'
            # uncomment this part to commit to the RAH repo as a particular author
            # RAH_CNAME: ''
            # RAH_CEMAIL: ''
            # RAH_ANAME: ''
            # RAH_AEMAIL: ''
            STORAGE_BUCKET: '{{bucket}}'
            STORAGE_REGION: '{{ecs.availabilityZone}}'

    ramFrontend:
      count: 1
      containers:
        ram-frontend:
          image: wbtransport/ram-frontend:latest-dev
          ports:
            - host: 80
              container: 80
              protocol: tcp
          apiMachine: api # name of the EC2 machine that the API is hosted on. Is used to set the machine's IP as the API address
          envs:
            MBTOKEN: '{{MB_TOKEN}}'
            RAH_URL: 'http://hub.ruralaccess.info'
    ramAnalysis:
      count: 0
      taskType: FARGATE
      cpu: 2048 # Cpu and Memory depend on each other - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html#cfn-ecs-taskdefinition-cpu
      memory: 6GB
      containers:
        ram-analysis:
          image: wbtransport/ram-analysis:latest-dev
          includeRds: true # set to true if RDS is used. DB_URI will be set automatically
          envs:
            STORAGE_ENGINE: s3
            STORAGE_BUCKET: '{{bucket}}'
            STORAGE_REGION: '{{ecs.availabilityZone}}'
    ramVectorTiles:
      count: 0
      taskType: FARGATE
      cpu: 2048 # Cpu and Memory depend on each other - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html#cfn-ecs-taskdefinition-cpu
      memory: 6GB
      containers:
        ram-vt:
          image: wbtransport/ram-vt:latest-dev
          envs:
            STORAGE_ENGINE: s3
            STORAGE_BUCKET: '{{bucket}}'
            STORAGE_REGION: '{{ecs.availabilityZone}}'
  tags:
    Project: ruralroads

ds-staging:
  stackName: ram-staging-deploy-cf

ram-demo:
  stackName: ram-demo-cf
  bucket: ram-demo
