default:
  stackName: ram-deploy-cf
  bucket: ram-cf-bucket 
  capabilities:
    - CAPABILITY_NAMED_IAM

  vpc:
    id: vpc-dfe524ba
    subnet: subnet-7945cb75

  ecs:
    publicIp: true # whether the ec2 instance have public IP addresses
    availabilityZone: us-east-1f # IMPORTANT: subnet and availability zone must be in the same zone
    amiid: ami-aff65ad2	 # which ec2 AMI to use for the ec2 instances
    instanceType: t2.small # size of the ec2 instance
    volumeSize: 30 # the size of the storage on the ec2 instance
    keyPairName: ruralroads # the ssh key to use for login into instance
    maxInstances: 1
    desiredInstances: 1

  taskDefinitions:
    ram:
      count: 0 
      networkMode: null
      volume:
        name: pos
        path: /var/lib/postgresql/data # this is the path on the source machine
      containers:
        ram-api:
          image: wbtransport/rra-api:latest-dev
          #cpu: 10 # this is an optional key
          memory: 500 # defaults to 256mb
          links:
            - ram-postgis
          ports:
            - host: 80
              container: 4000 
              protocol: tcp
          envs:
            ANL_CONTAINER: wbtransport/rra-analysis:latest-dev
            ANL_DB: 'postgresql://rra:rra@{{ANL_IP_ADDRESS}}:5432/rra'
            ANL_SERVICE: hyper
            DB_CONNECTION: 'postgresql://rra:rra@ram-postgis:5432/rra'
            DS_ENV: staging
            HYPER_ACCESS: '{{HYPER_ACCESS}}'
            HYPER_SECRET: '{{HYPER_SECRET}}'
            HYPER_SIZE: L3
            STORAGE_BUCKET: '{{STORAGE_BUCKET}}'
            STORAGE_REGION: '{{STORAGE_REGION}}'
            STORAGE_ACCESS_KEY: '{{STORAGE_ACCESS_KEY}}'
            STORAGE_SECRET_KEY: '{{STORAGE_SECRET_KEY}}'
          commands:
            - node
            - index.js
        ram-postgis:
          image: mdillon/postgis
          memory: 500 # defaults to 256mb
          mount:
            volume: pos
            destination: /var/lib/postgresql/data
          envs:
            POSTGRES_DB: rra
            POSTGRES_PASSWORD: rra
            POSTGRES_USER: rra

  tags:
    project: ruralroads

ds-staging:
  stackName: ram-staging-deploy-cf

aj-staging:
  stackName: aj-ram-staging
