default:
  stackName: ram-demo-test
  bucket: ram-demo-test # bucket with the CF config. Has to exist prior to deploying a stack
  capabilities:
    - CAPABILITY_NAMED_IAM

  vpc:
    id: vpc-dfe524ba
    subnet: subnet-7945cb75

  rds:
    type: db.t2.medium
    username: ram
    password: '{{DB_PASSWORD}}'
    dbName: ram
    engine: postgres
    version: '9.6.8'
    storage: 20

  s3:
    fileStorage:
      name: 'ram-filestorage-{{stackName}}'

  # instances created by this config are configured to work with ECS service
  ecs:
    publicIp: true # whether the ec2 instance have public IP addresses
    availabilityZone: us-east-1f # IMPORTANT: subnet and availability zone must be in the same zone
    amiid: ami-aff65ad2 # which ec2 AMI to use for the ec2 instances
    keyPairName: ruralroads # the ssh key to use for login into instance
    ec2:
      api:
        instanceType: t2.medium # size of the ec2 instance
        volumeSize: 30
      frontend:
        instanceType: t2.micro
        volumeSize: 8

  taskDefinitions:
    ramApi:
      count: 1
      volume:
        name: pos
        path: /var/lib/postgresql/data # this is the path on the source machine
      placeOn: t2.medium # refers to one of the ec2 machine in the ecs.ec2 section
      containers:
        ram-api:
          image: wbtransport/ram-backend:latest
          ports:
            - host: 80
              container: 4000 
              protocol: tcp
          commands:
            - node
            - index.js
          includeRds: true # set to true if RDS is used. DB_URI will be set automatically
          envs:
            INSTANCE_ID: '{{stackName}}'
            DS_ENV: staging
            RAH_GH_REPO: 'WorldBank-Transport/rah'
            RAH_GH_TOKEN: '{{RAH_GH_TOKEN}}'
            RAH_GH_PATH: 'app/assets/content/projects'
            # uncomment this part to commit to the RAH repo as a particular author
            # RAH_CNAME: ''
            # RAH_CEMAIL: ''
            # RAH_ANAME: ''
            # RAH_AEMAIL: ''
            STORAGE_ENGINE: s3
            STORAGE_BUCKET: '!Ref fileStorageS3'
            STORAGE_REGION: '{{ecs.availabilityZone}}'
            # environment variables the backend needs to spin up Fargate containers
            VT_TASK_DEF: '!Ref ramVectorTilesTaskDefinition'
            VT_AWS_LOG_GROUP: '!Ref CloudwatchLogsGroup'
            VT_SERVICE: aws
            ANL_TASK_DEF: '!Ref ramAnalysisTaskDefinition'
            ANL_AWS_LOG_GROUP: '!Ref CloudwatchLogsGroup'
            ANL_SERVICE: aws

    ramFrontend:
      count: 1
      placeOn: t2.micro
      containers:
        ram-frontend:
          image: wbtransport/ram-frontend:latest
          ports:
            - host: 80
              container: 80
              protocol: tcp
          apiMachine: api # name of the EC2 machine that the API is hosted on. Is used to set the machine's IP as the API address
          envs:
            MBTOKEN: '{{MB_TOKEN}}'
            RAH_URL: 'http://hub.ruralaccess.info'
            # Uncomment if you want to use a custom domain for the API, instead of the IP address that CF automatically sets for you.
            # This will not configure the DNS, which has to be done separately
            # API: 'http://api.custom-domain.org'

    ramAnalysis:
      count: 0
      taskType: FARGATE
      cpu: 1024 # Cpu and Memory depend on each other - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html#cfn-ecs-taskdefinition-cpu
      memory: 4GB
      containers:
        ram-analysis:
          image: wbtransport/ram-analysis:latest
          includeRds: true # set to true if RDS is used. DB_URI will be set automatically
          envs:
            STORAGE_ENGINE: s3
            STORAGE_BUCKET: '!Ref fileStorageS3'
            STORAGE_REGION: '{{ecs.availabilityZone}}'
    ramVectorTiles:
      count: 0
      taskType: FARGATE
      cpu: 256 # Cpu and Memory depend on each other - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html#cfn-ecs-taskdefinition-cpu
      memory: 1GB
      containers:
        ram-vt:
          image: wbtransport/ram-vt:latest
          envs:
            STORAGE_ENGINE: s3
            STORAGE_BUCKET: '!Ref fileStorageS3'
            STORAGE_REGION: '{{ecs.availabilityZone}}'
  tags:
    Project: ram

ram-another-instance:
  stackName: ram-another-instance
